name: Trigger auto deployment for marchina

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/marchina-AutoDeployTrigger-61b5581e-e0db-4517-8f26-f9495f406d13.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MARCHINA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MARCHINA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MARCHINA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: marchinaregistry.azurecr.io
          registryUsername: ${{ secrets.MARCHINA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MARCHINA_REGISTRY_PASSWORD }}
          containerAppName: marchina
          resourceGroup: marchina-rg
          imageToBuild: marchinaregistry.azurecr.io/marchina:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


